### ISSUE TITLE
Segmentation fault while running

### ISSUE THREAD

**Issue by Shuang1997** [VLOGroup/dvs-panotracking#8] opened 2021-11-08 16:54 UTC
Hi,

I successfully built dvs_panotracking, opened the GUI and loaded events from the file given by you. But it always reports the Segmentation fault (core dumped), then GUI interface closed automatically, without any other information. Could you please help me?

Thank you!

**Comment by reini1305** [comment] 2021-11-08 20:00
Hi! 
did you specify a camera calibration file when starting the GUI? I know it is not super clean, but if it is started without, it will crash with a segmentation fault :)

**Comment by Shuang1997** [comment] 2021-11-09 13:56
> Hi! did you specify a camera calibration file when starting the GUI? I know it is not super clean, but if it is started without, it will crash with a segmentation fault :)

Thanks for your reply.

Yes, I input `./live_tracking_gui ../data/calib_davis.txt` to launch the application, and got the following output:

`found 1 devices
device number=0 info= GeForce GTX 970M
199.092       0 132.192
      0 198.829 110.713
      0       0       1
camera size: 0*0
mosaic size: 800*400
radial: -0.368436
output pose path:`

I think the GUI was opened correctly. So, do you think the reason can be my laptop is not good enough for this algorithm?

**Comment by reini1305** [comment] 2021-11-09 19:28
No, your card should be perfectly capable. When you load the event file, does the loading finish (with a message in the statusbar at the bottom of the window)?

**Comment by Shuang1997** [comment] 2021-11-27 16:20
> No, your card should be perfectly capable. When you load the event file, does the loading finish (with a message in the statusbar at the bottom of the window)?

Yes, it shows that the loading finished

**Comment by ChannelG** [comment] 2022-05-01 15:45
Hello, is the problem solved? I have encountered the exact same problem and I don't know how to deal with it. Even I compile it in debug mode, there's no message coming up, so I totally have no idea what happened...

**Comment by reini1305** [comment] 2022-05-02 17:29
Hi! No, I didn't hear from the OP anymore. Can you give me more details of your setup (OS, CUDA, NVidia driver)? I'm trying to reproduce this on my Ubuntu 20.04 box with Cuda 11.6 and a Titan Xp, but here it works fine. I've started the GUI with 
`./live_reconstruction_gui ../data/config.txt` and loaded the sample `desk_swing.aer2` and got this reconstruction:
![image](https://user-images.githubusercontent.com/6517551/166295252-30560cea-2296-455b-9283-0c743c5990f2.png)
@Shuang1997 I've seen that you used the camera calib of the DAVIS camera, can you try again with the other? That also worked for me but just resulted in a not great reconstruction...

**Comment by Shuang1997** [comment] 2022-05-02 17:36
> 

Hi, thanks for contacting, The code works for me now. But I didn't work on the original code, it has been modified (more params are required from config.txt), If works for me after adding these params in the config.txt. As for the original version in this repo, I still fail to compile.

**Comment by ChannelG** [comment] 2022-05-03 04:09
@reini1305 my setup is ubuntu 18.04 with Cuda 10.2, RTX 2070s. Maybe the problem is as Shuang said, that the calib.txt missed some params. Could you have a look at that?

**Comment by reini1305** [comment] 2022-05-03 05:42
@Shuang1997 can you post your modified `config.txt` or what you had to change in the code? I couldn't reproduce the issue on my machine.

**Comment by Shuang1997** [comment] 2022-05-03 09:50
> @reini1305 my setup is ubuntu 18.04 with Cuda 10.2, RTX 2070s. Maybe the problem is as Shuang said, that the calib.txt missed some params. Could you have a look at that?

@ChannelG I do not know which version of the code are you working on. I think you can check this function: `void Parameters::readFromfile(std::string filename)` in the parameters.cpp, all parameters are loaded here. Then what you need to do is reformat your config.txt according to this function.

**Comment by reini1305** [comment] 2022-05-03 11:16
@Shuang1997 could you post the changes you had to make? This code is unchanged for more than 5 years and has been working for a variety of people, I'm wondering what happened that there are suddenly issues for @ChannelG and you?

**Comment by reini1305** [comment] 2022-05-08 18:11
I'm afraid I have to close this issue without additional information. Feel free to open again with details about I can fix this.

**Closed as completed by reini1305** 2022-05-08 18:11 UTC
